language: node_js

sudo: false

cache: 
    apt: true
    directory:
        - node_modules

node_js: stable

install: 
    - yarn
    - cd ./test/smoke/template/
    - yarn
    - cd ../
    - node index.js
    - cd ../../

script:
    - yarn run lint && yarn run test