language: node_js

sudo: false

cache: 
    apt: true
    directory:
        - node_modules

node_js: stable

install: 
    - npm install
    - cd ./test/smoke/template
    - npm install

script:
    - npm run lint && npm run test